Remove Initial Setup and anaconda-user-help packages from RHEL-10
minimization/content-resolver-input pull request #1025
Opened 2023-11-21 12:19 UTC by jkonecny12

See reasoning in commits.

2023-11-21 14:55 UTC, poncovka approved these changes
Thanks!

2023-11-28 16:25 UTC, yselkowitz requested changes
The config needs to be split out between c9s and eln, as this change should only apply to the latter.

2023-12-05 12:41 UTC, jkonecny12 commented
Is it better @yselkowitz now?

2023-12-05 23:45 UTC, yselkowitz approved these changes

2023-12-07 00:23 UTC, merged