s390utils is available for all arches
minimization/content-resolver-input pull request #1029
Opened 2023-11-28 12:19 UTC by sharkcz

Some of the tools from the s390utils source package are now built for all platforms, thus move the s390utils entry from the s390x section to the general one.

Related: https://issues.redhat.com/browse/RHEL-10567

2023-11-28 12:58 UTC, Conan-Kudo approved these changes
Yay, finally!

2023-11-28 20:34 UTC, yselkowitz requested changes
This config is used for both c9s and eln, but (at least so far) the multi-arch build changes are only in ELN.  Unless that is going to be backported to c9s, then the configs will need to be split.

2023-11-29 11:43 UTC, sharkcz commented
> This config is used for both c9s and eln, but (at least so far) the multi-arch build changes are only in ELN. Unless that is going to be backported to c9s, then the configs will need to be split.

We are enabling the all-arch builds for RHEL as well, please see the linked Jira ticket.

2023-11-29 15:10 UTC, yselkowitz approved these changes

2023-11-30 02:02 UTC, merged