Update .NET workload for CentOS Stream 10
minimization/content-resolver-input pull request #1040
Opened 2023-12-12 17:35 UTC by omajid

- Add .NET 8
- Drop .NET 6, and 7

2023-12-12 17:36 UTC, omajid commented on configs/sst_dotnet-dotnet.yaml
> -  arch_packages:
.NET 7 and later are available for all 4 architectures that Fedora/RHEL care about.

2023-12-12 17:43 UTC, yselkowitz requested changes
These config files are currently tagged both `eln` and `c9s`.  Therefore, the configs must be split, with the removals applying only to the eln config.

2023-12-12 19:10 UTC, omajid commented
> These config files are currently tagged both eln and c9s. Therefore, the configs must be split, with the removals applying only to the eln config.

Do we care about `c9s` in the context of minimization? Should I just remove `c9s` instead?

2023-12-12 20:31 UTC, yselkowitz commented
> Do we care about `c9s` in the context of minimization? Should I just remove `c9s` instead?

We are continuing to track c9s in CR at this time.  As these removals must only apply to ELN, the configs must be split, with the removals applying only to the eln config.  Of course, if/when dotnet8.0 is added to c9s as well, then it should also be added to the c9s configs, but the previous version, having already been shipped, must not be removed.

2023-12-12 20:44 UTC, omajid commented
Thanks for clarifying that. I have split up eln and c9s configuration.

2023-12-12 23:57 UTC, yselkowitz requested changes
One small nitpick, looks good otherwise.

2023-12-12 23:57 UTC, yselkowitz commented on configs/sst_dotnet-unwanted-eln.yaml
> +  description: Packages that .NET maintainers do not wish to maintain in RHEL 9
```suggestion
  description: Packages that .NET maintainers do not wish to maintain in RHEL 10
```

2023-12-13 13:28 UTC, yselkowitz approved these changes

2024-01-10 16:04 UTC, merged