eln-extras: update list of mailman3 packages
minimization/content-resolver-input pull request #1111
Opened 2024-03-16 16:57 UTC by michel-slm

(one-time formatting change, using POI tracker to generate the YAML)

2024-03-16 16:57 UTC, Conan-Kudo approved these changes

2024-03-27 21:13 UTC, yselkowitz requested changes
Please leave the formatting as it was.

2024-04-04 02:24 UTC, michel-slm commented
Ack, will adjust my tool to match the `yq` formatting

2024-07-23 14:17 UTC, yselkowitz commented
ELN Extras is being wound down in favour of an earlier EPEL; closing.

2024-07-23 14:17 UTC, closed without merging