Add kdump-utils subpackage to ELN and c10s.
minimization/content-resolver-input pull request #1136
Opened 2024-04-19 03:30 UTC by licliu

We added a new subpackage kdump-utils in Fedora and RHEL-10.

2024-04-23 07:23 UTC, baoquan-he commented
Please help handle and merge this asap, all CKI cases of kdump failed on FedoraELN since kdump-utils can't be found and installed.

2024-04-24 01:48 UTC, licliu commented
Hi @yselkowitz, could you please help to check this PR?

2024-04-24 04:04 UTC, baoquan-he approved these changes

2024-04-26 18:10 UTC, yselkowitz requested changes
I cannot find a `kdump-utils` RPM, do you mean `libkdumpfile-util`?

2024-04-28 02:22 UTC, licliu commented
> I cannot find a `kdump-utils` RPM, do you mean `libkdumpfile-util`?

We added it as a subpackage of kexec-tools, it is available in Fedora Rawhide and we will backport the patches to RHEL-10 later.
 
upstream: https://github.com/rhkdump/kdump-utils
fedora project: https://src.fedoraproject.org/rpms/kexec-tools

2024-05-02 15:44 UTC, yselkowitz approved these changes

2024-05-02 15:46 UTC, merged