Move scipy ownership from cs_apps to cs_plumbers
minimization/content-resolver-input pull request #1142
Opened 2024-04-26 12:58 UTC by psimovec

2024-04-26 19:27 UTC, yselkowitz requested changes

2024-04-26 19:27 UTC, yselkowitz commented on configs/sst_cs_plumbers-math-c9s.yaml
> +  description: Various math related libraries
These need to be changed so as not to conflict with your existing Math workload.  Perhaps this should be renamed to ATLAS (both here and -atlas in the file name).

2024-04-30 12:15 UTC, lzaoral commented
@psimovec `scipy` id now owned by plumbers in all releases.  Therefore, it should be added to the `c9s` yaml as well.

2024-05-01 11:14 UTC, psimovec commented
Thanks for the comments, I have simplified the changes

2024-05-02 17:34 UTC, merged