updates for libmemcached/libmemcached-awesome
minimization/content-resolver-input pull request #1145
Opened 2024-04-29 13:59 UTC by notroj

Update c9s workflows to reflect that libmemcached-awesome replaced libmemcached (from 9.0)

Update c10s+ workflows to remove libmemcached-awesome (RHEL-34695)

2024-05-02 17:32 UTC, yselkowitz requested changes

2024-05-02 17:32 UTC, yselkowitz commented on configs/sst_cs_infra_services-databases-c9s.yaml
> +    - c9s
```suggestion
  labels:
    - c9s
```

2024-05-08 13:42 UTC, notroj commented
Thanks @yselkowitz - adjusted as requested & rebased

2024-05-08 13:50 UTC, yselkowitz approved these changes

2024-05-08 13:50 UTC, merged