Unwanted: efs-utils + efs-utils-selinux
minimization/content-resolver-input pull request #1146
Opened 2024-04-30 12:41 UTC by major

We cannot package efs-utils and efs-utils-selinux any longer due to upstream changes.

2024-04-30 12:41 UTC, major commented
First time doing unwanted packages, so I'm not sure if I've done this correctly.

2024-05-02 17:21 UTC, yselkowitz requested changes
The existing efs-utils config(s) need to be removed instead.

2024-05-02 20:05 UTC, major commented
Thanks, @yselkowitz. I must have been following some old docs.

2024-05-03 11:14 UTC, yselkowitz approved these changes

2024-05-03 11:15 UTC, merged