Remove nvme-cli from sst_arch_hw_eln.yaml
minimization/content-resolver-input pull request #1152
Opened 2024-05-09 21:16 UTC by dledford

This package is not maintained by arch_hw.  It is required by anaconda-install-img-deps as shown by https://tiny.distro.builders/view-rpm--view-eln--nvme-cli.html and so will still be included in the install image.  If it is wanted post-install, then likely storage_ssg should pull it in as a requirement.

2024-05-09 22:19 UTC, yselkowitz requested changes
Unfortunately there is no dependency on nvme-cli in c10s, so this would cause it to fall of CR entirely, and (mistakenly) become a candidate for removal.  Let's get a new owner for this and move it to another workload instead.

While we're at it, perhaps we can get clarification on the inclusion of both nvme-cli and nvmetcli?

2024-05-13 14:53 UTC, dledford commented
> Unfortunately there is no dependency on nvme-cli in c10s, so this would cause it to fall of CR entirely, and (mistakenly) become a candidate for removal. Let's get a new owner for this and move it to another workload instead.

It's a hard runtime dependency of anaconda-install-image-deps, doesn't that keep it from falling off entirely?

> While we're at it, perhaps we can get clarification on the inclusion of both nvme-cli and nvmetcli?

I have pinged the manager of the NVME work being done about this and asked his input.  It may be that we move it to storage workload, or it may be that the nvmetcli is a replacement.  We'll wait and see.

2024-05-13 22:00 UTC, yselkowitz commented
> It's a hard runtime dependency of anaconda-install-image-deps, doesn't that keep it from falling off entirely?

Not in c10s: https://tiny.distro.builders/view-rpm--view-c10s--nvme-cli.html

2024-05-14 10:45 UTC, tbzatek commented
`nvme-cli` needs to be added to `sst_storage_io-packages.yaml` to reflect real ownership. Same should be done for `libnvme` to confirm explicit ownership.

2024-05-14 15:18 UTC, maurizio-lombardi commented
> `nvme-cli` needs to be added to `sst_storage_io-packages.yaml` to reflect real ownership. Same should be done for `libnvme` to confirm explicit ownership.

I opened a MR for that: https://github.com/minimization/content-resolver-input/pull/1159

2024-05-14 15:21 UTC, maurizio-lombardi commented
> While we're at it, perhaps we can get clarification on the inclusion of both nvme-cli and nvmetcli?

They are two completely different packages. There is no relationship between them.

2024-05-14 15:34 UTC, yselkowitz approved these changes
#1159 will keep this in the package set.

2024-05-14 15:39 UTC, merged