sst_csi_client_tools: add redhat-cloud-client-configuration
minimization/content-resolver-input pull request #1174
Opened 2024-05-28 07:12 UTC by ptoscano

This RHEL-only package exists already in 7, 8, and 9, and it was forgotten from 10. Hence, let's add it as placeholder package.

2024-05-28 11:12 UTC, yselkowitz commented on configs/sst_csi_client_tools.yaml
> +        - description: redhat-cloud-client-configuration
```suggestion
          description: Red Hat cloud client configuration
```

2024-05-28 11:15 UTC, yselkowitz requested changes

2024-05-28 11:35 UTC, ptoscano commented on configs/sst_csi_client_tools.yaml
> +        - description: redhat-cloud-client-configuration
we have the same also for other placeholders; is the proper description needed for them?

2024-05-28 11:36 UTC, ptoscano commented on configs/sst_csi_client_tools.yaml
> +            - systemd
> Placeholders cannot be safely listed as dependencies for other placeholders

then that this ought to be something for the checking script to verify ;-)

2024-05-28 12:54 UTC, yselkowitz commented on configs/sst_csi_client_tools.yaml
> +        - description: redhat-cloud-client-configuration
The important point here is that the dash needs to be removed.

2024-05-29 13:25 UTC, ptoscano commented on configs/sst_csi_client_tools.yaml
> +        - description: redhat-cloud-client-configuration
oh, now I see what you mean: I thought you were referring to the dashes in the description text, not the one accidentally before `description:`!

fixing it

2024-05-29 14:22 UTC, yselkowitz approved these changes

2024-05-29 14:22 UTC, merged