Remove yara from sst_csi_client_tools
minimization/content-resolver-input pull request #1331
Opened 2024-11-28 07:18 UTC by mhuth

2024-11-28 07:20 UTC, mhuth commented
@ptoscano please do the needful.

2024-11-28 07:50 UTC, ptoscano commented
While removing it from sst_client_tools is correct, it will drop it entirely from the distro. yara **must** be in a workload to be shipped.

If yara belongs to sst_insights, then please move it to that workload.

2024-11-28 07:54 UTC, mhuth commented
@ptoscano It belongs to platmgmt-ins-security which isn't listed as a group in the config directory.  But it is a rover group: https://rover.redhat.com/groups/group/platmgmt-ins-security

2024-11-28 08:51 UTC, ptoscano commented
> It belongs to platmgmt-ins-security which isn't listed as a group in the config directory.

As I said, it must belong to a RHEL SST.

2024-11-29 03:08 UTC, yselkowitz requested changes

2024-11-29 03:08 UTC, yselkowitz commented on configs/sst_insights.yaml
> +          dependencies: []
See https://github.com/minimization/content-resolver-input/pull/1294#pullrequestreview-2353177631

2024-11-29 04:20 UTC, yselkowitz approved these changes

2024-11-29 04:20 UTC, merged