Reflect the sst split of sst-virt-firmware from sst-virtualization in Content Resolver
minimization/content-resolver-input pull request #1339
Opened 2024-12-25 02:56 UTC by CongLi

2024-12-25 17:49 UTC, yselkowitz requested changes

2024-12-25 17:49 UTC, yselkowitz commented on configs/sst_virtualization-firmware.yaml
> +  maintainer: sst_virt_firmware
The convention is that filenames are prefixed with the SST name.  Therefore, this file should be named `sst_virt_firmware-SOMETHING.yaml`.

2024-12-26 02:17 UTC, CongLi commented
@yselkowitz  Thanks for the explanation ! MR has been updated accordingly.

2024-12-26 03:22 UTC, yselkowitz approved these changes

2024-12-26 03:22 UTC, merged