sst_java: Updating the JMC ELN workload to reflect changes in packaging
minimization/content-resolver-input pull request #924
Opened 2023-06-30 15:36 UTC by Josh-Matsuoka

- Removing the eclipse-pde and tycho packages since they're no longer needed and have been removed
- Correcting the SST name to sst_java
- Removing the JMC 7 module

2023-06-30 16:15 UTC, yselkowitz commented
Thanks for the PR.  Because these packages have been retired from Fedora and therefore is now way to build them for ELN, they will need changed to placeholders instead.

2023-06-30 18:37 UTC, yselkowitz requested changes

2023-06-30 18:37 UTC, yselkowitz commented on configs/sst_java-jmc-eln.yaml
> +        limit_arches: x86_64
The new placeholder format uses lists, e.g.: 

```suggestion
  package_placeholders: 
    - srpm_name: jmc
      build_dependencies:
      - desktop-file-utils
      - java-17-openjdk-devel
      - maven-local
      limit_arches:
      - x86_64
      rpms:
      - rpm_name: jmc
        description: JDK Mission Control package
        dependencies:
        - gtk3
        - java-17-openjdk
        - mesa-libGLU
        - webkit2gtk4.1
        limit_arches:
        - x86_64
      
    - srpm_name: jmc-core
      build_dependencies:
      - maven-local
      limit_arches:
      - x86_64
      rpms:
      - rpm_name: jmc-core
        description: JDK Mission Control core library
        dependencies: []
        limit_arches:
        - x86_64
```

2023-07-04 14:28 UTC, Josh-Matsuoka commented
@yselkowitz how does this look now?

2023-07-05 14:59 UTC, yselkowitz commented on configs/sst_java-jmc-eln.yaml
>      x86_64:
This is now empty and should be removed.

2023-07-05 15:42 UTC, yselkowitz approved these changes

2023-07-06 01:24 UTC, merged